name: development build

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "develop" ]
    paths-ignore: [ "docs/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code repository
        uses: actions/checkout@v3
        
      - name: run pre-commit
        uses: pre-commit/action@v2.0.3

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:

      - name: checkout code repository
        uses: actions/checkout@v3

      - name: build the stack
        run:  docker-compose -f app/compose.yml up -d --build

      - name: tear down the stack
        run:  docker-compose -f app/compose.yml down
